a = int (input("enter number a:"))
b = int (input("enter number b:"))

print("number a is:",a)
print("number b is:",b)
print("addition of a and b is:",a+b)
print("subtraction of a and b is:",a-b)
print("multiplication of a and b is:",a*b)
print("division of a and b is:",a/b)
print("modulus of a and b is:",a%b)
print("floor division of a and b is:",a//b)
print("exponentiation of a and b is:",a**b)
